require "config.options"
require "config.plugins"
require "config.colorscheme"
require "config.gitcommit"
require "config.completions"
require "config.keymaps"
require "config.lsp"
require "config.telescope"
require "config.treesitter"

